version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Cloud-Backend/Dockerfile
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 10s
      retries: 5
    networks:
      - app-net

  frontend:
    build:
      context: .
      dockerfile: Cloud-Frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      # Nouvelle variable pour getSimilarImages
      API_URL: http://backend:5000
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
